batch_size: 64
epochs: 1
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False
print_every_n_iters: 50
save_model: False

model:
  out_dim: 10
  base_model: "resnet18"

dataset:
  name: imagenet
  num_workers: 0

loss:
  temperature: 0.5
  use_cosine_similarity: True
  multi_loss: False
  multi_loss_weight: 1.0
  single_loss_weight: 1.0
