batch_size: 10
epochs: 80
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False

model:
  out_dim: 10
  base_model: "resnet18"

dataset:
  num_workers: 0

loss:
  temperature: 0.5
  use_cosine_similarity: True
