batch_size: 64
epochs: 10
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 1e-6
fp16_precision: False
print_every_n_iters: 10000
save_model: False
tune_params: False
lr: 0.01

model:
  out_dim: 10
  base_model: "cnn"

dataset:
  name: cifar10
  num_workers: 0
  augmentation: True

loss:
  temperature: 0.5
  use_cosine_similarity: True
  multi_loss: True
  multi_loss_weight: 0
  single_loss_weight: 1.0  # discarded: use 1.0 - multi_loss_weight instead
