batch_size: 128
epochs: 20
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False
log_dir: normal
tune_params: True

hybrid:
  switch_on: True
  return_origin: True
  kernel_size: [3, 3]
  weights: [0.5, 0.5]
  probs: 0.5

model:
  out_dim: 256
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (96,96,3)
  num_workers: 0
  valid_size: 0.05
  augmentation: True

loss:
  temperature: 0.5
  use_cosine_similarity: True
  mse_loss: True