batch_size: 256
epochs: 100
eval_every_n_epochs: 10
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
testing_phase: False
resume_saved_runs: False
verbose: False

hybrid:
  kernel_size: (15, 15)
  sigma: (1.5, 1.5)
  delta: 0.01
  probability: (1, 1, 1)  # (hybrid, CutMix, Mixup)
  triple_weights: [True, True, True, True, True]
  learning_rate: 0.0003

model:
  out_dim: 128
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (96,96,3)
  num_workers: 0
  valid_size: 0.05
  augmentation: True

loss:
  use_cosine_similarity: True
  loss_function: bce