batch_size: 256
epochs: 100
eval_every_n_epochs: 20
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
testing_phase: False

hybrid:
  kernel_size: 15
  delta: 0.01
  triple_weights: [1, 1, 1, 1]
  learning_rate: 0.0003

model:
  out_dim: 128
  base_model: "resnet18"


dataset:
  s: 1
  input_shape: (96,96,3)
  num_workers: 0
  valid_size: 0.05
  augmentation: True

loss:
  use_cosine_similarity: False